services:
  db:
    container_name: 'spboot_postgres'
    image: 'postgres:14'
    restart: always
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: