app:
  jwt:
    secret: ${JWT_SECRET:change-me-change-me-change-me-change-me} # ≥32 байт
    issuer: ${JWT_ISSUER:spring-boot-crud}
    access-min: 60
  auth:
    cookie-name: ACCESS_TOKEN
    cookie-domain: ${COOKIE_DOMAIN:localhost}   # прод: example.com
    cookie-secure: ${COOKIE_SECURE:true}        # prod=true, dev можно false
    cookie-same-site: Lax

spring:
  application:
    name: spring-boot-crud

  config:
    import: optional:file:./.env

  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: hackme

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  servlet:
    context-path: /v1/api